### ISSUE TITLE
Compile error for @Cacheable annotation when class is marked as @Transactional

### ISSUE THREAD

**Issue by av-m** [grails/grails-data-mapping#1087]
I have the same issue as reported by @davidbairdala in grails-plugins/grails-cache/issues/49
However I think this might be more directly related to GORM Transactional?

### Example
```groovy
import grails.gorm.transactions.Transactional
import grails.plugin.cache.*

@Transactional
class TestService {

    @Cacheable(value = 'testservice', key = { foobar } )
    String serviceMethod(String foobar) {
        return foobar
    }
}
```

```
[Static type checking] - The variable [foobar] is undeclared.
 @ line 7, column 47.
   alue = 'testservice', key = { foobar } )
```

Code compiles fine when using `org.springframework.transaction.annotation.Transactional`

### Environment Information
- **Operating System**: GNU/Linux 4.15.14-1-ARCH
- **GORM Version:** 6.1.9.RELEASE
- **Grails Cache Plugin Version:** 4.0.0
- **Grails Version:** 3.3.5
- **JDK Version:** openjdk 1.8.0_162

**Comment by demon101** [comment]
this bug also affects my project.
I think, New transactional AST transformation change signature of methods (parameters name)
In best case, transformations (transaction and cache) should save initial naming

**Comment by mkobel** [comment]
I can confirm the same issue as @av-m using the identical versions (Grails, GORM, grails-cache)

**Comment by puneetbehl** [comment]
This problem has been fixed in the cache plugin. Please try with `4.0.2.BUILD_SNAPSHOT` of `cache` plugin.

**Comment by mkobel** [comment]
Thank you.

I just tried with `compile "org.grails.plugins:cache:4.0.2.BUILD-SNAPSHOT"`, but I still got the same error.
The error is still there after upgrading Grails to 3.3.6 and GORM to 6.1.10.RELEASE.

Do you need additional information or can you give me a hint how I could figure out the cause of the not working solution?

**Comment by puneetbehl** [comment]
@mkobel  I am not seeing any issues, please check the [sample application.zip](https://github.com/grails/grails-data-mapping/files/2139367/cache-plugin-error.zip)

**Comment by mkobel** [comment]
I just tried again with two of my own projects. During the build gradle downloaded a new snapshot and it worked as expected. Thank you.
